### ISSUE TITLE
Define: Blueprint

### ISSUE THREAD

**Issue by rocketstack-matt** [finos/devops-automation#119]
## Architecture as Code: Glossary Definition
Please see [Architecture as Code: Glossary Definition](https://github.com/finos/devops-automation/issues/121) for details on how to help with this definition.

### Title
Blueprint

### Definition
Pre-authored and approved architectures available as documentation. Traditionally in the form of a static document describing an architecture but which would ideally be a machine readable descriptor of all details required to automatically instantiate a running instance of the described architecture.

**Comment by Madhurchandran** [comment]
#Define blueprint : blueprint is visualize model, architecture before creating a real time object.

**Comment by rocketstack-matt** [comment]
I like the two complementary defintions from the page you reference . . .

- a high-level, graphical or written piece of documentation of software architecture ("blueprint for humans")

- a piece of code serving as a template for code-generating tools that build or configure applications ("blueprint for machines")
