### ISSUE TITLE
Define: Digital Twin

### ISSUE THREAD

**Issue by rocketstack-matt** [finos/devops-automation#123]
## Architecture as Code: Glossary Definition
Please see [Architecture as Code: Glossary Definition](https://github.com/finos/devops-automation/issues/121) for details on how to help with this definition.

### Title
Digital Twin

### Definition
Electronic representations of our existing systems

**Comment by yt-ms** [comment]
I wonder whether we should be more specific about calling this a "Digital Architecture Twin", to differentiate from digital twins focused around simulating the real-life operations of businesses.

https://en.wikipedia.org/wiki/Digital_twin

**Comment by rocketstack-matt** [comment]
I think given this will be within the context of an Software Architecture glossary that's probably duplicative.

**Comment by yt-ms** [comment]
Well - except that an organisation may have or be building a digital twin for its operations as part of its architecture.  Maybe I'm overthinking this.

**Comment by mgasca** [comment]
I happen to agree with @yt-ms on this one with regards to disambiguation.  I don't think it necessarily has to be done in the term itself (i.e. the title), but the definition should detail that it is a digital twin of our living systems and not a digital twin of our business operations.
