### ISSUE TITLE
Define: Fitness Functions

### ISSUE THREAD

**Issue by rocketstack-matt** [finos/devops-automation#125]
## Architecture as Code: Glossary Definition
Please see [Architecture as Code: Glossary Definition](https://github.com/finos/devops-automation/issues/121) for details on how to help with this definition.

### Title
Fitness Functions

### Definition
Ability to map a systems documented architecture against verifiable fitness scores

**Comment by yt-ms** [comment]
A fitness function is a particular type of that is used to summarise, as a single [figure of merit], how close a given design solution is to achieving the set aims (1).

Ideally, fitness functions should describe the intent of the “-ility.” It addresses it in terms of an objective metric that is meaningful to product teams or stakeholders. Monitoring critical qualities as fitness functions can help product teams avoid architectural drift and objectively measure technical debt. (2)

The fitness function metaphor encompasses a variety of mechanisms we employ to ensure architecture doesn’t change in undesirable ways, including metrics, tests, and other verification tools. When an architect identifies an architectural characteristic they want to protect as things evolve, they define one or more fitness functions to protect that feature. (3)

References:
1. https://en.wikipedia.org/wiki/Fitness_function
2. https://www.thoughtworks.com/en-gb/insights/articles/fitness-function-driven-development
3. Ford, Parsons, Kua and Sadalage (2022), [_Building Evolutionary Architectures_, 2nd Edition](https://learning.oreilly.com/library/view/building-evolutionary-architectures/9781492097532/), O'Reilly
