### ISSUE TITLE
Architecture as Code - Working Group Meeting - Tuesday 24 Oct 2023

### ISSUE THREAD

**Issue by rocketstack-matt** [finos/devops-automation#144]
## Date

Tuesday 24 Oct 2023 - 11:00 EST / 16:00 UK

## Untracked attendees

| Name | Firm | Comment |
| :--- | :--- | :------ |

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies).

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda

- [x] Convene, roll call, welcome new people
- [x] Approve previous meeting minutes

**Architecture Logical Model**
- [x] Recap of Logical Architecture as Code Model (@dc-ms)
- [x] Overview of initial manifest proposal (@rocketstack-matt)
  - Modelling TraderX
  - JSON Schema
  - JSON vs. YAML Manifest
- [x] Domains (Aldwin Saugere)
  - Core vs Domains
  - Deep Dive Security Domain
  - Other Potential Domains
- [x] Identification of initial functional capabilities - call for contribution

**AOB**
- [x] On-site Accelerator - moved to October 30th
- [x] AOB, Q&A & Adjourn (5mins)

### Zoom info

**Join Zoom Meeting**
- https://zoom.us/j/95521041942?pwd=dHgwREU2TzBsS242ak1zYWZsUW9OUT09
- Meeting ID: 955 2104 1942
- Passcode: 443820
- Find your local number: https://zoom.us/u/aesEqmNODb

**Github Repo:** https://github.com/finos/devops-automation/

**Project Board:** https://github.com/orgs/finos/projects/33

**Mailing List:** Email devops-mutualization+subscribe@finos.org to subscribe to our mailing list

**Comment by dc-ms** [comment]
Denis Coffaro - Morgan Stanley

**Comment by rocketstack-matt** [comment]
Matthew Bain / Morgan Stanley

**Comment by eteridvalishvili** [comment]
Eteri / FINOS

**Comment by RichardWagener365** [comment]
Richard Wagener / Cognizant

**Comment by davidilles** [comment]
David Illes / Morgan Stanley

**Comment by rocketstack-matt** [comment]
See attached presentation from the meeting - [2023-10-24.pdf](https://github.com/finos/devops-automation/files/13120631/2023-10-24.pdf)

**Comment by mgasca** [comment]
Miguel Gasca / Morgan Stanley

**Comment by rocketstack-matt** [comment]
**FINOS Meeting: October 24, 2023**
 
**Commenced**: 11:04 EST
 
Previous minutes approved by attendees and closed out (Issue 138) : Approved
 
**Logical Architecture as Code Model: Recap** - @dc-ms
•	Principles - Simplicity, Scalability and Flexibility
•	Capabilities - the functionality we want to build and serve
•	Domains - Technical zone with unique boundaries

**Initial Core Manifest Walkthrough** - @rocketstack-matt 
•	Apply the model to TraderX

**_Nodes_**:
•	Nodes capture capability
•	Something to logically represent at different levels
•	Feature/Component/Container/User/Process/Network
**_Relationships_**:
•	Relationship provide multi-dimensional view across architectures
•	How things interact with each other
•	Trader interacting with a web client
•	Web client connecting to web gui
•	Logical vs. Physical deployment
•	Q: MG on how to manage dependency vs. data flow identification?
•	Follow Up : MG to share his view, lessons learned and ideas

**Security Domain perspective** - Aldwin
•	Review of demo on previous meeting
•	Domain - published extension to common language solving wide scale use cases
•	Potential domains proposed - looking for feedback
•	Security domain in scope

- Firewall - risks and control vulnerabilities
- Example of consumer flow by firewall service
- Control array usage by types
- Sub schema on additional domains
•	Extensions - enable capabilities specific to users or applications
- Leveraged to promote or enhance domains
- Particular use case - firm or business unit specific

**General Conversation**:
•	Q: RICKA how well do you think this scales, do developers live in the JSON?
•	Q: MG We won't capture validations or evidence? 
•	MB: Managed externally but open for dialog and debate.
•	Q: MG Mitigation and ADR linkage.
•	MB: Usage of this model is to live with source code
 
**Actions**:
MG - Share how he would envision how to manage data flow properties.
October 30th - Onsite session in Morgan Stanley's London office
 
Adjourned at 11:58 EST

**Comment by rocketstack-matt** [comment]
Approved at WG 2023-11-28
