### ISSUE TITLE
Architecture as Code - On-site Accelerator

### ISSUE THREAD

**Issue by rocketstack-matt** [finos/devops-automation#145]
## Date

Monday 30th October - 09:00 - 12:30 UK

## Registration & Location

Please register your interest in the comments to this issue if you would like to attend. This meeting will be in-person in London, no remote facilities will be provided.

## Agenda
- Introductions
- Recap of the logical model
- Review of the current manifest
- Deep dive into the security domain 
- Break
- White boarding / brain storming on domains and capabilities
- Wash-up
- Close

**Comment by ojeb2** [comment]
Link to the whiteboard I shared at 10.30am:
https://www.tldraw.com/r/R5W4522-umF6yre2S-cdn?viewport=-8%2C116%2C1212%2C676&page=page%3Apage

**Comment by rocketstack-matt** [comment]
# Minutes

On Monday 30th October we held our first in-person accelerator session, hosted at Morgan Stanley's Cabot Square office, with representatives from LSEG, Barclays and Deutsche as well as Morgan Stanley itself.

![E3ED0116-B2E5-4513-AF8D-7CADC87FCE61_1_105_c](https://github.com/finos/devops-automation/assets/66839492/0d94b35c-047f-4a98-b419-e51b7d6fe1e3)

The first part of the accelerator was used to ensure everyone present was up to speed with the progress to date, both in terms of how the logical model is proposed and how that informs the creation of the [manifest](https://github.com/finos/devops-automation/tree/main/aasc).

![Screenshot 2023-11-03 at 11 12 12](https://github.com/finos/devops-automation/assets/66839492/e015c059-dc86-4d7e-bb19-248116c3ad3b)

The second part was used to brainstorm how the team see the model evolving, especially in regards to the additional domains that could be required to support the multitude of use cases we could see this model supporting and how they could manifest in terms of capabilities (functional implementations driving real world use under-pinned by the model).

![6FA7A7DD-FA3E-46E3-994F-B5B310362C60_1_105_c](https://github.com/finos/devops-automation/assets/66839492/6cfad4cc-2b86-4ed3-9925-6342489e24fd)

## Domains & Capabilities

### Deployment
![A0EFD8CB-39A6-45B3-8E9B-3154C3E9D5E6_1_105_c](https://github.com/finos/devops-automation/assets/66839492/4aa2293c-1b55-4341-87d9-690fe6ebec71)

### Data
![3783018B-7DD6-4152-B7C3-8EB863406F03_1_105_c](https://github.com/finos/devops-automation/assets/66839492/8a7250cf-4ab9-45e4-92e3-0bf726d8a19a)

### Operational Resilience
![76CAD4EC-7D2C-48A7-A9E2-E1ADE2DE0F49_1_105_c](https://github.com/finos/devops-automation/assets/66839492/fb96ea50-bffb-4b27-b8c6-54c00b6aa187)

### Security
![B1DA0F3B-4435-430A-AF1E-3CD7EFBC0700_1_105_c](https://github.com/finos/devops-automation/assets/66839492/ca435b98-c5e8-42a9-9783-4d5b9d7cc820)

**Comment by rocketstack-matt** [comment]
Thanks for the updates @mgasca - closing as approved.
