### ISSUE TITLE
Architecture as Code - Working Group Meeting - Tuesday 23 Jan 2024

### ISSUE THREAD

**Issue by rocketstack-matt** [finos/devops-automation#175]
## Date

Tuesday 23 Jan 2024 - 11:00 EST / 16:00 UK

## Untracked attendees

| Name | Firm | Comment |
| :--- | :--- | :------ |

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies).

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda

- [x] Convene, roll call, welcome new people
- [x] Approve previous meeting minutes
- [x] Overview of the new Architecture as Code Monorepo
- [x] Rebranding of the AasC manifest as CALM (Common Architecture Language Model) - naming kudos to @dc-ms 
- [x] Confirm key project / subgroups and agree cadence / contribution commitments
- [x] AOB, Q&A & Adjourn (5mins)

## Decisions Made

- [ ] Decision 1
- [ ] Decision 2
- [ ] ...

## Action Items

- [ ] Action 1
- [ ] Action 2
- [ ] ...

### Zoom info

**Join Zoom Meeting**
- https://zoom.us/j/94904595244
- Meeting ID: 949 0459 5244
- Passcode: 545224
- Find your local number: https://zoom.us/u/aesEqmNODb

**Github Repo:** https://github.com/finos/devops-automation/

**Project Board:** https://github.com/orgs/finos/projects/33

**Mailing List:** Email devops-mutualization+subscribe@finos.org to subscribe to our mailing list

**Comment by rocketstack-matt** [comment]
Matthew Bain / Morgan Stanley

**Comment by jpgough-ms** [comment]
Jim Gough / Morgan Stanley

**Comment by sgm-ms** [comment]
Steve Mackenzie / Morgan Stanley

**Comment by arhy** [comment]
Alex Armstrong / Morgan Stanley

**Comment by rvema** [comment]
Ragha Vema | Fannie Mae

**Comment by dc-ms** [comment]
Denis Coffaro / Morgan Stanley

**Comment by fleureedwards** [comment]
Fleur Edwards | Nomura

**Comment by rocketstack-matt** [comment]
Minutes courtesy @dc-ms 

FINOS Meeting: January 23, 2024
 
Commenced: 11:06 EST
 
Introduction / FINOS Disclaimer: Completed
 
Previous minutes approved by attendees and closed out (Issue 154) : Approved
 
AaC Mono Repo Update : https://github.com/finos-labs/architecture-as-code 
Documentation Update: https://finos-labs.github.io/architecture-as-code/ 
 
What's the commitment level of people and code (contributions): SM / MB
•	Domain specific work groups 
•	Governance Group
 
Looking to build a translator between C4 and CALMS
•	Translate between OSS
 
What's our goal : Frank Schawillie / MB
•	Machine readable architecture description enabling
o	Approved vs. Deployed - Drift detection
o	Automation - IaC
o	DC to sync up with FS
•	CALM - Common Architecture Language Model
 
Walk through
•	Data
o	Work in progress internally
•	Business Domain
o	Capabilities
•	People, Process, Technology
o	Capability mapping to applications
•	Layer control
•	Process mapping 
•	Infrastructure as Code
o	Matt Gardner - update via comments
 
Actions:
•	NY meetup DC : DC
•	London meetup  : MB
•	Group framework and process - how do we operate in domains : MB
 
 
Adjourned: 11:44 EST

**Comment by rocketstack-matt** [comment]
Approved in WG 2024-02-27
