### ISSUE TITLE
DevOps Automation SIG Meeting - March 21, 2024 

### ISSUE THREAD

**Issue by ashukla13** [finos/devops-automation#182]
## Date

Thursday, March 21 2024 - 12pm ET; 4pm UK

## Untracked attendees

| Name | Firm | Comment |
| :--- | :--- | :------ |

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies).

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda

- [ ] Convene, roll call, welcome new people
- [x] Approve [previous meeting minutes](https://github.com/finos/devops-automation/issues/179#issuecomment-1946652749)
- [x]  Working Group updates
    - [ ] [Architecture as Code ](https://devops.finos.org/docs/working-groups/aasc)- @rocketstack-matt / @yt-ms 
    - [ ] [Backstage ](https://devops.finos.org/docs/working-groups/backstage/)- @cnygardtw
    - [ ] [OSS Supply Chain Risk Management ](https://devops.finos.org/docs/working-groups/osssc)- @johnmark 
    - [ ] [Automated Change Deployment](https://devops.finos.org/docs/working-groups/acm) - @rvema 
- [x] #181 
- [x] Approaches on Deprecation of Programming Languages and Tech Stacks - NatWest
## Decisions Made

- [ ] Decision 1
- [ ] Decision 2
- [ ] ...

## Action Items

- [ ] Action 1
- [ ] Action 2
- [ ] ...

### Zoom info

**Join Zoom Meeting**
- https://zoom.us/j/94904595244
- Meeting ID: 949 0459 5244
- Passcode: 545224
- Find your local number: https://zoom.us/u/aesEqmNODb

**Github Repo:** https://github.com/finos/devops-automation/

**Project Board:** https://github.com/orgs/finos/projects/33

**Mailing List:** Email devops-mutualization+subscribe@finos.org to subscribe to our mailing list

**Comment by rvema** [comment]
Ragha Vema | Fannie Mae

**Comment by ashukla13** [comment]
amol shukla/morgan stanley

**Comment by karlmoll** [comment]
Karl Moll / FINOS

**Comment by mcleo-d** [comment]
James McLeod / NatWest

**Comment by mcleo-d** [comment]
Wilson Sinclair / NatWest

**Comment by alvin-c-shih** [comment]
Alvin Shih / Morgan Stanley

**Comment by karlmoll** [comment]
Attended:
Frank Schawillie - RBC

**Comment by ashukla13** [comment]
**Minutes**

- Updates from working group
   - @rvema  raised question on raising surveys on specific topics like change mgmt approach at members. @mcleo-d  raised prior surveys including OSS readiness and also the annual surveys; also brought up getting information through informal demos and knowledge sharing through meeting. Discussion on potentially merging the Software supply chain and automated change deployment working group perspective - since the software supply chain seems to have traction
   - @ashukla13 provided a summary of #183 
   - @karlmoll  summarized Arch as code working group meetings - lots of demos and lively discussion
   - @karlmoll  summarzied Backstage working group meeting - including RedHat led discussion and reinforced interest in Backstage in FSI.  @mcleo-d  reiterated strategic importance of Backstage. Discussion on whether SIG should developer portal broadly - not just Backstage. @ashukla13  to raise this with @cnygardtw  at the next meeting

**Comment by rocketstack-matt** [comment]
Matthew Bain / Morgan Stanley

**Comment by karlmoll** [comment]
Code Generation Indemnity Further Reading referenced on today's call

Existing policies:
https://blogs.microsoft.com/on-the-issues/2023/09/07/copilot-copyright-commitment-ai-legal-concerns/
https://cloud.google.com/blog/products/ai-machine-learning/protecting-customers-with-generative-ai-indemnification

Reporting coverage:
https://www.runtime.news/ai-vendors-promised-indemnification-against-copyright-lawsuits-the-details-are-messy/
https://learn.g2.com/ai-code-generators-legal-considerations
