### ISSUE TITLE
Architecture as Code - Working Group Meeting - Tuesday 27 Feb 2024

### ISSUE THREAD

**Issue by rocketstack-matt** [finos/devops-automation#184]
## Date

Tuesday 27 Feb 2024 - 11:00 EST / 16:00 UK

## Untracked attendees

| Name | Firm | Comment |
| :--- | :--- | :------ |

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies).

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda

- [x] Convene, roll call, welcome new people
- [x] Approve previous meeting minutes - https://github.com/finos/devops-automation/issues/175 
- [x] Update on new JSON Meta Schema & Vocabulary for CALM (@rocketstack-matt )
- [x] Demo of using the new schema to model TraderX (@rocketstack-matt )
- [x] Developing reusable architecture patterns (@jpgough-ms)
- [x] Demo of advanced schema validation using Spectral (@willosborne)
- [x] Demo of a sample CALM visualizer (@aidanm3341)
- [x] Proposal for E2E solution based on TraderX (@matthewgardner)
- [x] Save the Date! Onsite Accelerator in London (@ojeb2)
- [ ] AOB, Q&A & Adjourn (5mins)

## Decisions Made

- [ ] Decision 1
- [ ] Decision 2
- [ ] ...

## Action Items

- [ ] Action 1
- [ ] Action 2
- [ ] ...

### Zoom info

**Join Zoom Meeting**
- https://zoom.us/j/94904595244
- Meeting ID: 949 0459 5244
- Passcode: 545224
- Find your local number: https://zoom.us/u/aesEqmNODb

**Github Repo:** https://github.com/finos/devops-automation/

**Project Board:** https://github.com/orgs/finos/projects/33

**Mailing List:** Email devops-automation+subscribe@finos.org to subscribe to our mailing list

**Comment by karlmoll** [comment]
Karl Moll / FINOS

**Comment by rocketstack-matt** [comment]
Matthew Bain / Morgan Stanley

**Comment by Budlee** [comment]
Matthew Auburn / Morgan Stanley

**Comment by willosborne** [comment]
Will Osborne / Morgan Stanley

**Comment by jpgough-ms** [comment]
Jim Gough / Morgan Stanley

**Comment by eddie-knight** [comment]
:wave: :shipit: Eddie Knight / Sonatype

**Comment by aidanm3341** [comment]
Aidan McPhelim / Morgan Stanley

**Comment by AttilaMihaly** [comment]
Attila Mihaly / Morgan Stanley

**Comment by lionking421** [comment]
Prashant Jasani / Morgan Stanley

**Comment by arhy** [comment]
Alex Armstrong / Morgan Stanley

**Comment by matthewgardner** [comment]
Matthew Gardner/Morgan Stanley

**Comment by lpaul1** [comment]
Louis Paul / Prudential

**Comment by jpgough-ms** [comment]
From my demo

* The issue for background: https://github.com/finos-labs/architecture-as-code/issues/11
* The pattern: https://github.com/finos-labs/architecture-as-code/blob/main/calm/pattern/api-gateway.json
* The instantiation of the pattern: https://github.com/finos-labs/architecture-as-code/blob/main/calm/samples/api-gateway-implementation.json

**Comment by yt-ms** [comment]
Yan Tordoff / Morgan Stanley

**Comment by dc-ms** [comment]
Denis Coffaro / Morgan Stanley

**Comment by rocketstack-matt** [comment]
As mentioned at the end of the call, we plan to run a second onsite accelerator courtesy of @ojeb2, please reply to this issue - https://github.com/finos/devops-automation/issues/185 - if you would like to attend.

**Comment by mgasca** [comment]
Miguel Gasca / Morgan Stanley

**Comment by rocketstack-matt** [comment]
**FINOS Meeting**: February 27, 2024
 
**Commenced**: 11:05 EST
 
**Introduction / FINOS Disclaimer**: Completed
 
**Previous minutes approved by attendees and closed out (Issue 175)** : Approved

**Matthew Bain** : Schema walkthrough and refactoring
                                 TraderX walkthrough
                                 JSON schema and auto populate of required files, e.g. nodes, relationships

**Jim Gough** : How do we model a pattern using the CALMS schema
                          API example and value of including the JSON schema

**Will Osbourne** : Validation process extended to structural analysis
                                Spectral to lint API specs and define
                                Definitions in YAML
                                Spectral demo with custom definitions

**Aidan McPhelim**: TraderX example visualization
                                  Right click on object to get properties

**Matthew Gardner**: Manifest to Infrastructure
                                    - Terraform Run - Infrastructure
                                    - YAML deployment configs - Application

**Comments/Feedback**:
Make more consistent with C4 visualization – Yan Tordoff 
Make it use C4 and looking at good things from C4 and incorporate – Yan Tordoff 
Maybe a “C4 mapper” feature – Matt Bain           

Contributions should be forked and not branched
Changes to specifications will be a formal/agreed process 
Position on language standards 

**Adjourned**: 12:02 EST

**Comment by rocketstack-matt** [comment]
Approved in #189
