### ISSUE TITLE
Architecture as Code: Onsite Accelerator - London 2024-03-12

### ISSUE THREAD

**Issue by rocketstack-matt** [finos/devops-automation#185]
## Signup

As mentioned in the Working Group call on 2024-02-27 @ojeb2 has kindly offered to host a second onsite accelerator. Please comment with your name and company on this issue if you would like an opportunity to attend.

**When** Tuesday 12th March 2024, 15:00 - 18:00
**Where** City of London (address will be confirmed to attendees)

**Comment by mgasca** [comment]
Miguel Gasca/Morgan Stanley

**Comment by pratikthanki** [comment]
Pratik Thanki / Trayport

**Comment by arhy** [comment]
Alex Armstrong / Morgan Stanley

**Comment by aidanm3341** [comment]
Aidan McPhelim / Morgan Stanley

**Comment by matthewgardner** [comment]
Matthew Gardner/Morgan Stanley

**Comment by rocketstack-matt** [comment]
Matthew Bain / Morgan Stanley

**Comment by yt-ms** [comment]
Yan Tordoff / Morgan Stanley

**Comment by jpgough-ms** [comment]
James (Jim) Gough / Morgan Stanley 

-- James only if you need ID 😄

**Comment by aldwins-ln** [comment]
Aldwin Saugere / Morgan Stanley

**Comment by rocketstack-matt** [comment]
Event is taking place tomorrow as planned. All folks on this thread have been registered and should have received details on the location.

**Comment by rocketstack-matt** [comment]
# Minutes

On Tuesday 12th January we were very kindly hosted by @ojeb2 at the London Stock Exchange Group in Paternoster Square.

![16434BC6-8DFC-4860-B3D6-FEC0FF2551DD_1_105_c](https://github.com/finos/devops-automation/assets/66839492/7787ade5-966c-481c-b296-69be71796e1d)


![218EB600-7B3A-47A9-81FC-8E6D3DA80623_1_105_c](https://github.com/finos/devops-automation/assets/66839492/3f209af1-1e24-4851-90ed-bc4224ea7fde)

For the first part of the meet-up we recapped the progress that has been made in the last couple of months, where we seem to be on a great upwards trajectory of contribution and development.

@rocketstack-matt first gave an overview of the migration of CALM to be a JSON Meta Schema and associated vocabulary and the rationale for doing do, namely it enabled the development of new schemas as patterns. @jpgough-ms delved deeper into how this enables us to develop architecture patterns that are far more opinionated rather than being mere base schemas to be extended and we were able to live demo the cool code completion features this gives us in JSON aware IDEs such as IntelliJ and VS Code.

Next up we had two cool demos showing the fledgling visualisation capabilities. First @aidanm3341 showed us his native rendering of CALM via a VS Code extension.

![image](https://github.com/finos/devops-automation/assets/66839492/3ebb546b-e23f-460e-a964-05b0724fcb61)

Then @Budlee was able to demonstrate the new translator service mapping CALM to the well used C4 model.

![92C42F3D-0E53-4413-8530-405CE0B7608D_1_105_c](https://github.com/finos/devops-automation/assets/66839492/655a47f5-2fc4-4f77-b80b-6e68e7b6a693)

Next on the agenda was a discussion around Composable Interfaces - in other words how could we combine architecture specifications into more complex interacting schemas. The initial discussion was focused around the existing [api-pattern](https://github.com/finos-labs/architecture-as-code/blob/main/calm/pattern/api-gateway.json) and how it is in effect an architecture description of systems that in themselves should have complex CALM representations.

![C071CFDA-34DD-46C9-B62A-E16CE67A01A3_1_105_c](https://github.com/finos/devops-automation/assets/66839492/9484e0d9-9487-482d-8a5f-993d83ba9256)

There was a long and detailed discussion, far too long to capture here, but you can see the full detail of what was captured for consideration on [this issue](https://github.com/finos-labs/architecture-as-code/issues/48).

Following a brief hiatus to grab coffee, we entered into a discussion on the need to start looking at the control requirements aspect of architecture. The control requirements are the aspects of policies and governing bodies for architectures that are to be built / deployed to ensure they fulfil necessary regulatory, audit or firm standards requirements.

@rocketstack-matt was able to give a little background on a conversation we had with another partner organisation the week prior where we were fortunate to be given a behind the curtains peek at some work that company has already done on capturing the control requirements and policy aspects of architectures as code. Whilst we can't reveal any more in the minutes at this point in time we're hopeful that partner org will be able to come to a future meet-up soon to reveal more and perhaps even some contributions to bootstrap this aspect of the architecture model.

As we neared the end of the event, we moved to @jpgough-ms to walk through another proposal for a new feature, this time that of a new [CLI capability](https://github.com/finos-labs/architecture-as-code/issues/53) which would allow for the rapid bootstrapping of architecture instantiations and could also act as the foundations for a broader array of CLI functions.

The final sections of the meet-up led to a call for continued commitment and finally a brainstorming session where we captured ideas for new features and folks signed up to write up the issues for them ahead of the next working group - you know who you are!

![F99EF667-2BC0-4237-99F3-AB0AF880619E_1_105_c](https://github.com/finos/devops-automation/assets/66839492/603a44a9-a991-495f-b975-d8faf8a9381a)

As we wrapped, we were super fortunate to be meeting on the same day as LSEG were also hosting the [London Enterprise Technology Meet Up](https://enterprisetech.london/event/) where we were able to decamp for a drink and debrief before some fascinating insight into the Digital Operational Resiliency Act (DORA), but we'll leave that for another post!

Thanks again to @ojeb2 and LSEG!

**Comment by Budlee** [comment]
Great write up of the event

**Comment by ojeb2** [comment]
added https://github.com/finos-labs/architecture-as-code/issues/84 to capture the Data Catalog / Lineage integration issue from the action board.
